[workspace]
resolver = "2"
members = [
    "tosho",
    "tosho_musq",
    "tosho_kmkc",
    "tosho_amap",
    "tosho_sjv",
    "tosho_rbean",
    "tosho_mplus",
    "tosho_macros",
    "tosho_common",
]

[workspace.package]
version = "0.6.2-dev"
edition = "2021"
authors = ["noaione <noaione@n4o.xyz>"]
license = "MIT"
repository = "https://github.com/noaione/tosho-mango"
homepage = "https://tosho.dev"
rust-version = "1.80.0"

[workspace.dependencies]
# Tokio related
tokio = { version = "1.39.3", features = ["full"] }
futures-util = "0.3"

# JSON/Protobuf related
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
prost = "0.13.1"

# Utilities
anyhow = "1"
base64 = "0.22.1"
sha2 = "0.10.8"
time = "0.3.36"
chrono = "0.4.38"
rand = "0.8.5"

# HTTP related
reqwest = { version = "0.12.7", features = ["rustls-tls", "socks", "stream"] }
reqwest_cookie_store = "0.8.0"

# Image
image = { version = "0.25.2", default-features = false, features = ["jpeg", "png", "rayon"] }
kamadak-exif = "0.5.5"

# CI-PROFILE-MARK
