# The following Actions/Workflow is to test tosho with latest nightly Rust compiler.
# This is to ensure that tosho is always compatible with the latest Rust compiler.
name: Nightly Check
on:
  # Run every 3 days at 00:00 UTC
  schedule:
    - cron: '0 0 */3 * *'
  # Manual trigger
  workflow_dispatch:

env:
  RUST_BACKTRACE: full
  CARGO_TERM_COLOR: always
  PKG_CONFIG_SYSROOT_DIR: /
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          submodules: 'true'

      - name: Rustup nightly
        run: |
          rustup update nightly
      
      - name: Test and Build
        run: |
          cargo +nightly test --verbose --all
          cargo +nightly build --release --verbose --all
